inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: "2.6"

Security/MarshalLoad:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
